{% set name = "requests-async" %}
{% set version = "0.6.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f128b66dec2974aa263e24410914b1829d3e1506497364c2edfa10112f55e0b

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - http3 ==0.6.*
    - python >={{ python_min }}
    - requests ==2.*

test:
  requires:
    - python {{ python_min }}
  imports:
    - requests_async

about:
  home: https://github.com/encode/requests-async
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE.md
  summary: async-await support for `requests`.

extra:
  recipe-maintainers:
    - nicoddemus
    - wiphoo
